spring.datasource.url=jdbc:mysql://localhost:3306/retro_database
spring.datasource.username=root
spring.datasource.password=1234

jwt.access.key=bsdfjhfsccwyvvfsd
jwt.refresh.key=sbwyuvg8g8c8vuvdf

jwt.access.expiration=1800
jwt.refresh.expiration=259200
springdoc.swagger-ui.path=/swagger-ui.html

issuer=retro-api

cloudinary.url=cloudinary://756296278366286:7_13d_NuL9ZwKXehASV5Z9_cEL0@dpuakafvm